- src/data-display/tables/data-table/PDataTable.vue
PDataTable 컴포넌트의 th에 sticky position 추가
[[CONSOLE] DataTable 테이블헤더가 고정되어야함](https://pyengine.atlassian.net/browse/CLOUD-3875)
- .p-data-table .th에 `position: sticky`와 `top: 0` 추가
- sticky가 적용되면, copy 아이콘을 눌렀을 때 'copied!' 텍스트가 잘려보이는 경우가 있음(copied! 텍스트가 th를 벗어날 경우)
- 이 문제 때문에 sticky를 없앴던 건데, 없애니까 스크롤 시 th 고정이 안 되어 다시 부활시킴.
- copied 텍스트를 정상적으로 보여줄 방법을 찾아야 함
> Add sticky position to PDatatable

- src/feedbacks/modals/button-modal/PButtonModal.stories.mdx
- src/feedbacks/modals/button-modal/PButtonModal.vue
- src/feedbacks/modals/button-modal/type.ts
- src/inputs/context-menu/PContextMenu.vue
- src/inputs/context-menu/type.ts
- src/inputs/dropdown/dropdown-btn/PDropdownBtn.vue
- src/inputs/dropdown/dropdown-btn/type.ts
- src/inputs/dropdown/dropdown-menu-btn/PDropdownMenuBtn.vue
- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- src/inputs/dropdown/select-dropdown/type.ts
모달의 DropdownMenuBtn 컴포넌트 개선
https://pyengine.atlassian.net/browse/CLOUD-4311
- 모달의 DropdownMenuBtn 컴포넌트의 메뉴 리스트가 뷰 바깥으로 나가지 않고, 모달 위로 올라오도록 개선
- 현재 DropdownMenuBtn이 있는 모달에 스크롤이 되는 경우가 거의 없는데, 모달내 스크롤시 펼쳐져 있던 메뉴리스트가 숨겨지는 코드를 포함시키는게 좋을지 모르겠음.
- 기존 메뉴리스트(PContextMenu)의 autoHeight 스타일 주는것과 이번에 개발된 코드랑 같이 정리할 필요가 있어보임.
> Add using custom style of dropdown in modal

- src/data-display/tree/PTree.vue
PTree 컴포넌트에 node-folded-changed 이벤트 사용
node-folded-changed 이벤트를 사용함으로써 drag할 때 정상적으로 unfold 기능이 작동합니다!
> Add node-folded-changed event to PTree

- src/inputs/buttons/select-button-group/PSelectButtonGroup.stories.mdx
- src/inputs/buttons/select-button-group/PSelectButtonGroup.vue
- src/inputs/buttons/select-button-group/config.ts
- src/inputs/buttons/select-button-group/type.ts
PSelectButtonGroup에 theme('default' | 'text') 추가
~~buttonType~~ **theme** props를 추가하여 스타일을 변경할 수 있도록 수정했습니다.
> feat: add theme to PSelectButtonGroup

- src/data-display/collapsibles/collapsible-list/PCollapsibleList.stories.mdx
- src/data-display/collapsibles/collapsible-list/PCollapsibleList.vue
- src/data-display/collapsibles/collapsible-panel/PCollapsiblePanel.stories.mdx
- src/data-display/collapsibles/collapsible-panel/PCollapsiblePanel.vue
- collapsible panel 에 show/hide 버튼을 text overflow 상태를 감지하여 선택적으로 표시하는 기능 추가
- collapsible panel 에 line clamp negative case 추가
- collapsible list 에서 collapsible panel 을 사용하도록 변경
> feat: add text overflow detection to collapsible panel

- src/data-display/badges/PBadge.vue
- src/data-display/dynamic/dynamic-layout/templates/item/index.vue
- src/data-display/tables/definition-table/PDefinitionTable.stories.mdx
- src/data-display/tables/definition-table/PDefinitionTable.vue
- src/data-display/tables/definition-table/config.ts
- src/data-display/tables/definition-table/definition/PDefinition.stories.mdx
- src/data-display/tables/definition-table/definition/PDefinition.vue
- src/data-display/tables/definition-table/definition/story-helper.ts
- src/data-display/tables/definition-table/story-helper.ts
- src/data-display/tables/definition-table/type.ts
- src/inputs/anchors/PAnchor.vue
- src/others/console/text-list/PTextList.vue
- definition table 컴포넌트에 반응형 스타일, styleType, disableCopy props 추가
- 슬롯 추가(key, extra)
- 리팩토링
> feat: add resposive styles, style type, disable copy to definition table

- src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.ts
- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- src/inputs/dropdown/select-dropdown/type.ts
PSelectDropdown에서 PDropdownMenuBtn을 사용하던 것을 삭제 (PDropdownMenuBtn 컴포넌트는 그대로 있음!)
- 일부 클래스명 수정(btn > button, is-invalid-btn > invalid)
- 거의 대부분 그대로 옮겼습니다.
- emit event를 할 때 input과 onSelected 두 개를 같이 사용하는데, input만 남겼으면 좋겠습니다. (콘솔에서 사용하는 곳이 있어서 차차 수정해야 할듯)
- 전반적인 리팩토링 필요할듯 (디자인, 이벤트 처리 등)
> refactor: PSelectDropdown

- src/data-display/badges/PBadge.vue
- src/data-display/progress-bar/PProgressBar.vue
- src/data-display/status/PStatus.vue
- src/data-display/tags/PTag.vue
- src/feedbacks/alert/notice/PNoticeAlert.vue
- src/feedbacks/alert/toast/PToastAlert.vue
- src/feedbacks/loading/skeleton/PSkeleton.vue
- src/feedbacks/modals/button-modal/PButtonModal.vue
- src/feedbacks/modals/icon-modal/PIconModal.vue
- src/inputs/buttons/button/PButton.vue
- src/inputs/buttons/copy-button/PCopyButton.vue
- src/inputs/buttons/icon-button/PIconButton.vue
- src/inputs/buttons/select-button-group/PSelectButtonGroup.vue
- src/inputs/input/PTextInput.vue
- src/inputs/search/query-search-tags/PQuerySearchTags.vue
- src/inputs/search/search/PSearch.vue
- src/inputs/select-card/PSelectCard.vue
- src/layouts/pane-layout/PPaneLayout.vue
- 전체 컴포넌트 border radius 디자인 변경사항 반영
- tailwind css 방식으로 변경
deprecated 예정인 dropdown menu btn 컴포넌트를 제외하고 모두 반영하였습니다.
다음 스프린트에 dropdown menu btn  컴포넌트를 제거하고 select dropdown 컴포넌트로 변경하겠습니다.
> feat: update border radius style

- src/feedbacks/modals/button-modal/PButtonModal.stories.mdx
- src/feedbacks/modals/button-modal/PButtonModal.vue
- src/feedbacks/modals/button-modal/type.ts
- src/hooks/context-menu-custom-style/index.ts
- src/hooks/context-menu-custom-style/story-helper.ts
- src/inputs/context-menu/type.ts
- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- src/inputs/dropdown/select-dropdown/type.ts
- src/inputs/search/autocomplete-search/PAutocompleteSearch.stories.mdx
- src/inputs/search/autocomplete-search/PAutocompleteSearch.vue
- src/inputs/search/autocomplete-search/story-helper.ts
- context menu custom style hook 에서 scrollable parent 를 찾아, 있는 경우에는 자동으로  context menu 를 닫아주는 기능 추가
- use custom style -> use fixed menu style 로 props 명 변경
selectable dropdown, autocomplete search 컴포넌트에서 use custom style -> use fixed menu style 로 props 이름을 변경했습니다.
use fixed menu style 을 true 로 주면, 아래의 기능이 동작하게 됩니다.
1. menu 가 position fixed 로 동작
2. scrollable parent 에 scroll 이벤트 발생 시, menu  자동으로 닫음 
이에 따라 button modal 에서 scroll 이벤트 관련된 동작을 모두 삭제했습니다.
> feat: add auto hide in context menu custom style hook

- src/inputs/buttons/toggle-button/PToggleButton.stories.mdx
- src/inputs/buttons/toggle-button/PToggleButton.vue
PToggleButton에서 제가 없애버렸던 sync props를 되살렸습니다.
> fix: add sync props to PToggleButton

- src/inputs/search/autocomplete-search/PAutocompleteSearch.vue
- autocomplete search 의 menu 가 left 고정 값이 없어서 추가함 (없으면 모바일 등에서 예상치 못한 경우가 생김)
> fix: autocomplete search menu set left position

- src/inputs/select-card/PSelectCard.vue
PSelectCard disabled 일경우 border-color
- PSelectCard  selected 와 disabled를 동시에 적용할 경우 border-color가 selected-border(border-secondary)로 적용되어 수정
> feat: add disabled border-color to PSelectCard

- package-lock.json
- package.json
- src/data-display/tree/PTree.stories.mdx
- src/data-display/tree/PTree.vue
- src/data-display/tree/type.ts
- tree 컴포넌트에  walk tree data 메소드 추가
- get all nodes, get all items 의 복잡한 로직 리팩토링. 내부 로직을 walk tree data 를 사용하도록 변경함.
- tree 컴포넌트에서 addChildNodeByPath 후 추가한 아이템 레퍼런스를 찾지 못하는 버그 수정
> feat: add walk tree data method to tree and refactor some methods

- src/data-display/tree/PTree.stories.mdx
- src/feedbacks/loading/lazy-img/PLazyImg.stories.mdx
- src/feedbacks/loading/lazy-img/PLazyImg.vue
- src/feedbacks/loading/lazy-img/story-helper.ts
- src/inputs/select-card/PSelectCard.stories.mdx
- src/inputs/select-card/PSelectCard.vue
- src/inputs/select-card/story-helper.ts
- lazy img 컴포넌트에 error icon color props 추가
- select card 컴포넌트에 icon color props 추가
- select card 에 무조건 icon 컬러가 고정되는 버그 수정
- select card icon props 에 boolean 타입 추가(기본 아이콘 사용하는 경우)
> feat: add icon color to select card and error icon color to lazy img

- src/inputs/buttons/copy-button/PCopyButton.vue
- copy button style inline flex 에서  inline block 으로 변경
> fix: change copy button from inline flex to inline block

- src/data-display/titles/page-title/PPageTitle.vue
- src/data-display/titles/panel-top/PPanelTop.vue
- src/util/helpers.ts
panel-top의 total-count에 표기법 (comma)추가 했습니다.
콘솔 페이지에서 commaFormatter로 추가 했더니 타입오류가 났습니다.
컴포넌트의 total-count props 타입은 Number 인데, 페이지에서 commaFormatter로 바꾸는 과정에서 String이 되는걸로 확인했어요~!
해당 스펙은 컴포넌트에 포함 되도 좋을것 같아서 디자인 시스템에 추가하는게 어떨가 싶습니다.
> fix: add commaFormatter to total count

- src/data-display/tree/PTree.stories.mdx
- src/data-display/tree/PTree.vue
- src/data-display/tree/he-tree-vue/plugins/draggable/Draggable.vue
- src/data-display/tree/he-tree-vue/plugins/fold.ts
- src/data-display/tree/he-tree-vue/types.ts
- src/data-display/tree/he-tree-vue/utils.ts
- src/data-display/tree/type.ts
1. update-drag 제거
2. drop 이벤트에 rollback 파라미터 추가
3. drop, end-drag 이벤트 파라미터, dragOptions.dropValidator, dragOptions.endValidator 함수 아규먼트에 oldParent 추가
라이브러리를 내장화하면서 타입스크립트가 미적용되어 버그 발생 가능성이 늘어나, 필요한 수준만큼만 적용
https://user-images.githubusercontent.com/26986739/150271151-9ad3d1c8-171b-464a-809e-4e05e5351a22.mov
> fix: add rollback cb function to drop event param in tree

- src/inputs/text-editor/PTextEditor.stories.ts
- src/inputs/text-editor/PTextEditor.vue
- src/inputs/text-editor/config.ts
> fix: make inherit min height of parent element in TextEditor

- src/inputs/context-menu/context-menu-item/PContextMenuItem.vue
In the past, internal elements were created as slots using the <router-link> component unconditionally.
However, if the slot prop is not used, a problem that appears to be a bug in the <router-link> component occurred, such as the listener not working properly.
To solve this, adding unused slot props is not a good way, so we looked for another way.
If there is no link, there is no reason to use the <router-link> component, so when there is no link, the <span> tag is used.
---
기존에는 무조건 `<router-link>` 컴포넌트를 사용하여 slot으로 내부 요소를 작성했습니다. 
그런데 slot prop을 사용하지 않으면 리스너가 제대로 동작하지 않는 등 `<router-link>` 컴포넌트의 버그로 보이는 문제가 발생했습니다.
이를 해결하기 위해 사용하지 않는 slot prop을 추가하는 것은 좋은 방법이 아니라서 다른 방법을 모색하였습니다.
link 가 없는 경우에는 `<router-link>` 컴포넌트를 사용할 이유가 없으므로, link 가 없는 경우에는 `<span>` 태그를 사용하도록 수정하였습니다.
> fix: don't use router-link if link is not given in ContextMenuItem

- src/data-display/dynamic/dynamic-field/PDynamicField.stories.mdx
- src/data-display/dynamic/dynamic-field/PDynamicField.vue
- src/data-display/dynamic/dynamic-field/templates/more/index.vue
- src/data-display/dynamic/dynamic-field/templates/more/type.ts
- src/data-display/dynamic/dynamic-field/type/field-schema.ts
- src/data-display/dynamic/dynamic-field/type/index.ts
- src/data-display/dynamic/dynamic-layout/PDynamicLayout.stories.mdx
- src/data-display/dynamic/dynamic-layout/PDynamicLayout.vue
- src/data-display/dynamic/dynamic-layout/PDynamicLayoutPlayground.stories.mdx
- src/data-display/dynamic/dynamic-layout/mock.ts
- src/data-display/dynamic/dynamic-layout/story-helper.ts
- src/data-display/dynamic/dynamic-layout/templates/html/html.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/item/item.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/list/list.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/markdown/markdown.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/popup/index.vue
- src/data-display/dynamic/dynamic-layout/templates/popup/popup.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/popup/story-helper.ts
- src/data-display/dynamic/dynamic-layout/templates/popup/type.ts
- src/data-display/dynamic/dynamic-layout/templates/query-search-table/query-search-table.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/raw-table/raw-table.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/raw/raw.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/simple-table/simple-table.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/table/table.stories.mdx
- src/data-display/dynamic/dynamic-layout/type/index.ts
- src/data-display/dynamic/dynamic-layout/type/layout-schema.ts
> feat: add more type to DynamicField & add popup type to DynamicLayout

- src/inputs/search/query-search/PQuerySearch.vue
- src/navigation/toolbox/PToolbox.vue
- query search: make only !. != operators available in null case
- toolbox: make use value label when initiating query tags (there was a bug not using value label when value set is empty)
> feat(query search): make only !. != operators available in null case

- src/inputs/search/query-search-tags/PQuerySearchTags.vue
- src/inputs/search/query-search-tags/helper.ts
- src/inputs/search/query-search/type.ts
- src/navigation/toolbox/PToolbox.vue
- toolbox: use default converter if value set is not exist 
- query search tags: do not watch array directly
> fix(toolbox): use default converter if value set is not exist & fix(query search tags): do not watch array directly

- src/feedbacks/modals/button-modal/PButtonModal.stories.mdx
- src/feedbacks/modals/button-modal/PButtonModal.vue
- src/feedbacks/modals/button-modal/story-helper.ts
- src/feedbacks/modals/modal.pcss
To use button-modal as popup, it is needed `position` attribute
If `position` prop is served, set button-modal `position: absolute; left: {position}rem; right: {position}rem`
* On mobile, `left` is always 0.75rem when `position` prop is served
> feat(button-modal): add spec of ```position``` for popup

- src/data-display/popover/PPopover.stories.mdx
- src/data-display/popover/PPopover.vue
- src/data-display/popover/story-helper.ts
- src/data-display/popover/type.ts
- Add `isVisible` prop to Popover component (two-way binding with `update:is-visible` event)
- Remove `scoped` from style of Popover component
- Add event and missing prop to Popover component storybook ArgsTable
- Changed Popover component to use `defineComponent` and other refactorings
- Update images (assets head update)
--- 
- Popover 컴포넌트에 `isVisible` prop 추가 (`update:is-visible` 이벤트로 양방향 바인딩)
- Popover 컴포넌트의 스타일에서 `scoped` 삭제
- Popover 컴포넌트 스토리북 ArgsTable에 이벤트 및 누락된 prop 추가
- Popover 컴포넌트 `defineComponent` 사용하도록 변경 및 기타 리팩토링
- 이미지 업데이트 (에셋 헤드 업데이트)
> feat(popover): add isVisible prop to Popover component

- src/inputs/forms/new-json-schema-form/PJsonSchemaForm.stories.mdx
- src/inputs/forms/new-json-schema-form/PJsonSchemaForm.vue
- src/inputs/forms/new-json-schema-form/localize.ts
- src/inputs/forms/new-json-schema-form/story-helper.ts
- src/inputs/forms/new-json-schema-form/type.ts
- src/inputs/forms/new-json-schema-form/validation.ts
By adding the `language` prop, the three languages (en, ko, jp) supported by the design system are reflected in the validation result message.
---
`language` prop을 추가하여 validation 결과 메시지에 디자인 시스템이 지원하는 3개 언어(en, ko, jp)가 반영되도록 적용함
> feat(json-schema-form): add language prop to support i18n
