- organisms/definition/PDefinition.vue
- organisms/forms/dynamic-form/PDynamicForm.vue
- organisms/tables/data-table/PDataTable.vue
* Add: validationMode props to PDynamicForm
* Update: minor things
> Feature/components (#93)

- organisms/tables/query-search-table/PQuerySearchTable.md
- organisms/tables/query-search-table/PQuerySearchTable.vue
- organisms/tables/query-search-table/type.ts
addTag, deleteTag, deleteAllTag
> QuerySearchTable: added functions

- organisms/dynamic-field/PDynamicField.vue
addTag, deleteTag, deleteAllTag
> DynamicField: handler bug fixed

- organisms/search/query-search-tags/helper.ts
- allowed date and datetime format
> QuerySearchTags: upated default converter for datetime 

- package-lock.json
- package.json
- src/molecules/text-editor/text-editor/PTextEditor.stories.ts
- src/molecules/text-editor/text-editor/PTextEditor.vue
- src/molecules/text-editor/text-editor/config.ts
> UpdatedTextEditor: make force import codemirror in every instance

- package-lock.json
- package.json
- src/molecules/text-editor/text-editor/PTextEditor.vue
> Initate versioning

- src/data-display/tables/data-table/PDataTable.stories.ts
- src/data-display/tables/data-table/PDataTable.vue
DataTable > invald case 에 요소 선택 안되는 버그 수정
> Fix not selecting problem when invalid bug in Datatable

- src/feedbacks/modals/icon-modal/PIconModal.vue
> Fix icon modal scoped style

- src/inputs/input/PTextInput.vue
Update right slot default css to TextInput
> Update right slot default css to TextInput

- src/data-display/dynamic/dynamic-field/type/field-schema.ts
Refactor dynamic field enum options type
> Refactor dynamic field enum options type

- src/foundation/lottie/PLottie.vue
- src/inputs/anchors/PAnchor.vue
- src/inputs/forms/field-group/PFieldGroup.stories.mdx
- src/inputs/forms/field-group/PFieldGroup.vue
- src/inputs/forms/json-schema-form/PJsonSchemaForm.vue
- src/others/console/modals/double-check-modal/PDoubleCheckModal.vue
FieldGroup 에 이밴트, 슬롯 추가
Lottie 버그 수정
- Lottie: 같은 이름을 가진 모든 로티 컴포넌트가 unmounted 시 함꼐 삭제되는 버그 수정(uuid 로 삭별하여 destory)
- FieldGroup
- click-label 이벤트 추가
- label-extra 슬롯 추가
> Add few features to FieldGroup and fix Lottie bug

- src/feedbacks/modals/button-modal/PButtonModal.stories.ts
- src/feedbacks/modals/button-modal/PButtonModal.vue
- src/feedbacks/modals/button-modal/type.ts
- src/feedbacks/modals/modal/PModal.vue
- src/feedbacks/modals/type.ts
- src/others/console/modals/double-check-modal/PDoubleCheckModal.vue
- src/others/console/modals/double-check-modal/type.ts
- src/others/console/modals/table-modal/PTableCheckModal.stories.ts
- src/others/console/modals/table-modal/PTableCheckModal.vue
Modal 작업
Modal에서 필요없는 props들 삭제
> Remove unnecessary props

- src/styles/colors.js
color palette 추가
https://pyengine.atlassian.net/browse/CLOUD-3217
peacock 컬러 추가
> Add peacock color

- src/navigation/toolbox/PToolbox.vue
> Fix minor bug in toolbox

- src/layouts/vertical-layout/PVerticalLayout.vue
vertical layout
https://pyengine.atlassian.net/browse/CLOUD-4205
vertical layout css 수정
> Fix vertical layout css

- src/inputs/buttons/toggle-button/PToggleButton.vue
- src/inputs/buttons/toggle-button/config.ts
토글 버튼 theme 추가
토글 버튼 peackok-500 theme 추가
> Add toggle button theme

- src/layouts/vertical-layout/PVerticalLayout.vue
Vertical layout 수정
Vertical layout css 수정 (position: absolute -> position: sticky)
> Fix minor style bug in vertical layout

- AUTHORS
> Add contributors

- src/inputs/search/query-search/PQuerySearch.vue
검색 컴포넌트의 붙여 넣기 기능 추가
[CLOUD-4047](https://pyengine.atlassian.net/browse/CLOUD-4047)
query search 컴포넌트에 'key:value' 형태로 붙여넣기 하였을 때, 자동으로 key와 value를 감지하여 insert 되도록 반영하였습니다.
> Add text paste case to query search

- src/inputs/buttons/select-button-group/PSelectButtonGroup.vue
SelectedButtonGroup에 border-transparent 넣음
> Change border color of SelectedButtonGroup

- src/feedbacks/alert/toast/PToastAlert.vue
Toast alert 컴포넌트 
Loading 타입 추가
컴포넌트 디자인 변경
> Update toast alert component

- src/data-display/tree/PTree.vue
- add get all items including nodes and paths
- add delete node method
- enable bulk add nodes and child nodes
> Update tree methods

- src/navigation/toolbox/PToolbox.vue
Toolbox component css 수정
https://pyengine.atlassian.net/browse/CLOUD-4362
> Fix toolbox component css

- src/inputs/buttons/select-button-group/PSelectButtonGroup.vue
> Change PSelectButton color

- src/data-display/tables/toolbox-table/PToolboxTable.vue
PToolbodTable에서 페이지 이동 시 체크박스 해제
> Remove selectIndex items when page is moved

- src/data-display/dynamic/dynamic-layout/helper.ts
Add temporary code for tags path in dynamic layout value extract helper
> Add temporary code for tags path in dynamic layout value extract helper

- src/feedbacks/modals/icon-modal/PIconModal.stories.ts
- src/feedbacks/modals/icon-modal/PIconModal.vue
Icon modal 작업 
Icon modal에 md 작업 추가
> feat: add md style type to icon modal

- CHANGELOG.md
- package-lock.json
- package.json
- src/inputs/buttons/button/PButton.stories.mdx
- src/inputs/buttons/button/PButton.vue
- src/inputs/buttons/button/type.ts
- src/inputs/buttons/icon-text-button/PIconTextButton.vue
- src/styles/colors.js
> feat: add font weight props and secondary color to Button 

- src/inputs/buttons/button/PButton.stories.mdx
- src/inputs/buttons/button/PButton.vue
- src/inputs/buttons/button/type.ts
- src/inputs/buttons/icon-text-button/PIconTextButton.vue
- src/styles/colors.js
> feat: add font weight props, secondary dark color type to button

- src/layouts/sidebar/PSidebar.stories.mdx
- src/layouts/sidebar/PSidebar.vue
- src/layouts/sidebar/type.ts
사이드바에 styletype 추가
https://pyengine.atlassian.net/browse/CLOUD-4439
- 핸드북용 사이드바 styletype 추가
> feat: add styletype props to sidebar

- src/inputs/anchors/PAnchor.vue
add white space nowrap to anchor text
> fix: update css of anchor text

- src/data-display/raw-data/PRawData.vue
- src/feedbacks/modals/icon-modal/PIconModal.vue
Component refactoring 작업
1. Raw data component에 string 타입 추가
2. icon modal이 scroll되지 않는 이슈 수정
> fix: update type in raw data component and modal overflow property

- src/inputs/anchors/PAnchor.vue
- src/inputs/search/autocomplete-search/PAutocompleteSearch.vue
- src/inputs/search/autocomplete-search/helper.ts
- src/inputs/search/autocomplete-search/type.ts
> fix: fix autocomplete search bugs and handler usage

- src/layouts/sidebar/PSidebar.vue
> fix: update css of sidebar

- src/data-display/status/PStatus.vue
> fix: PStatus icon color

- .github/workflows/workflow.yml
github action 작업 
Github action에 node_modules 관련 캐싱 적용
> feat: add caching job to github action workflow

- .github/workflows/workflow.yml
> feat: add caching to github action

- .github/workflows/test_workflow.yml
- .github/workflows/workflow.yml
> feat: test github action workflow

- .github/workflows/test_workflow.yml
> feat: test github action

- .github/workflows/test_workflow.yml
> fix: github action workflow

- src/feedbacks/modals/icon-modal/PIconModal.vue
icon modal css 수정
icon modal div 구조로 인한 스크롤 버그 수정
> fix: update css of icon modal

- src/others/console/modals/table-modal/PTableCheckModal.vue
> fix: add loading props to table check modal

- src/inputs/buttons/select-button-group/PSelectButtonGroup.stories.mdx
- src/inputs/buttons/select-button-group/PSelectButtonGroup.vue
PSelectButtonGroup 버그 수정
[[DESIGN-SYSTEM] PSelectButtonGroup 버튼 수정](https://pyengine.atlassian.net/browse/CLOUD-4619)
> fix: delete display:flex from PSelectButtonGroup

- src/navigation/tabs/ballon-tab/PBalloonTab.stories.mdx
- src/navigation/tabs/ballon-tab/PBalloonTab.vue
- src/navigation/tabs/ballon-tab/config.ts
- src/navigation/tabs/ballon-tab/story-helper.ts
- src/navigation/tabs/tab/PTab.stories.mdx
- src/styles/screens.js
- tailwind.config.js
> feat: add balloon tab component

- src/index.ts
> fix: add Balloon Tab to index

- src/data-display/status/PStatus.stories.mdx
- src/data-display/status/PStatus.vue
- src/inputs/select-status/PSelectStatus.stories.mdx
- src/inputs/select-status/PSelectStatus.vue
- src/inputs/select-status/story-helper.ts
> feat: add select status component

- src/hooks/select/story-helper.ts
- src/index.ts
- src/inputs/input/PTextInput.vue
- src/inputs/textarea/PTextarea.stories.mdx
- src/inputs/textarea/PTextarea.vue
- src/inputs/textarea/story-helper.ts
> feat: add textarea component

- src/data-display/collapsibles/collapsible-list/PCollapsibleList.stories.mdx
- src/data-display/collapsibles/collapsible-list/PCollapsibleList.vue
- src/data-display/collapsibles/collapsible-list/config.ts
- src/data-display/collapsibles/collapsible-list/story-helper.ts
- src/index.ts
> feat: add collapsible list component

- src/index.ts
> feat: export list card component

- src/inputs/select-status/PSelectStatus.stories.mdx
- src/inputs/select-status/PSelectStatus.vue
- src/inputs/select-status/story-helper.ts
> feat: add disableCheckIcon props to PSelectStatus

- src/data-display/cards/card/story-helper.ts
- src/data-display/cards/list-card/PListCard.vue
> feat: fix card styles

- src/inputs/select-button/PSelectButton.vue
피그마대로 text color와 hover color를 수정했습니다.
> fix: PSelectButton color

- src/data-display/cards/list-card/PListCard.stories.mdx
- src/data-display/cards/list-card/PListCard.vue
- src/data-display/cards/list-card/story-helper.ts
**hoverable** props 추가 및 hover 스타일 적용
hoverable 디폴트값은 false 입니다.
> feat: add hoverable props to PListCard

- src/data-display/cards/list-card/PListCard.vue
PListCard의 li에 @click 이벤트 추가
PListCard 사용시 리스트 아이템을 클릭 시 다른 페이지로 이동하는 경우가 많아 추가하게 됨
> feat: add click event to PListCard

- src/inputs/buttons/button/PButton.vue
outline button disabled style 추가
- outline버튼이 disabled 일 경우, 적용되는 스타일 추가
> feat: add disabled outline button style

- src/hooks/tab/story-helper.ts
- src/navigation/tabs/ballon-tab/PBalloonTab.stories.mdx
- src/navigation/tabs/ballon-tab/story-helper.ts
- src/navigation/tabs/box-tab/PBoxTab.stories.mdx
- src/navigation/tabs/box-tab/story-helper.ts
- src/navigation/tabs/button-tab/PButtonTab.stories.mdx
- src/navigation/tabs/button-tab/story-helper.ts
- src/navigation/tabs/tab/PTab.stories.mdx
- src/navigation/tabs/tab/PTab.vue
- src/navigation/tabs/tab/story-helper.ts
> feat: add extra slot to tab

- src/data-display/cards/card/PCard.vue
> fix: white space between header and border

- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
> fix: update select dropdown component spec

- src/hooks/context-menu-fixed-style/index.ts
- src/inputs/anchors/PAnchor.vue
- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- src/inputs/forms/field-group/PFieldGroup.stories.mdx
- src/inputs/radio/PRadio.vue
- src/inputs/search/autocomplete-search/PAutocompleteSearch.vue
- tailwind.config.js
일부 input 컴포넌트들의 focus, active 상태의 css style 을 변경하였습니다.
> fix: update input components focus style

- src/feedbacks/modals/button-modal/PButtonModal.vue
- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
> fix: dropdown and modal css

- src/data-display/tree/PTree.vue
tree 컴포넌트에 여러 노드를 찾아서 선택상태로 만드는 함수를 추가
> feat: add fetch and find nodes to tree

- src/hooks/tab/index.ts
- src/navigation/tabs/tab/type.ts
> feat: add beta tag in tab

- src/inputs/select-card/PSelectCard.vue
> feat: add default icon in p select card

- src/inputs/buttons/toggle-button/PToggleButton.stories.mdx
- src/inputs/buttons/toggle-button/PToggleButton.vue
- src/inputs/buttons/toggle-button/type.ts
feat: add disabled props to PToggleButton
> feat: add disabled props to PToggleButton

- src/inputs/forms/json-schema-form/PJsonSchemaForm.vue
json schema form에 pattern 에러 메시지 추가
> feat: add pattern invalid message

- src/inputs/radio/PRadio.vue
> fix: vertical-align in PRadio

- src/inputs/select-card/PSelectCard.vue
- src/util/helpers.ts
- select card 컴포넌트 selected 상태 마커에 반영 안되는 버그 수정
> fix: select card not binding marker bug fix

- src/styles/reset.pcss
button, input 클릭시 outline:none, 키보드로 탭 이동시 outline 보이기
> feat: hide outline on click

- src/data-display/tables/data-table/PDataTable.vue
- src/inputs/buttons/copy-button/PCopyButton.stories.mdx
- src/inputs/buttons/copy-button/PCopyButton.vue
- src/inputs/buttons/copy-button/story-helper.ts
- src/inputs/buttons/icon-text-button/PIconTextButton.vue
- fix: update icon text button disabled color
- fix: data table with field width case css bug fix
> fix: data table with field width case css bug fix

- src/inputs/buttons/button/PButton.vue
small button padding-x 값 수정
https://pyengine.atlassian.net/browse/CLOUD-4637
> fix: fix padding-x of small button

- src/data-display/cards/card/PCard.stories.mdx
> feat: add card without header

- src/hooks/tab/index.ts
- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- src/inputs/search/search/PSearch.vue
- src/navigation/tabs/tab/type.ts
- src/navigation/toolbox/PToolbox.stories.mdx
- src/navigation/toolbox/story-helper.ts
- tab 에서 isBeta 스펙 제거
- toolbox story bug fix
- search focus style fix (outline제거)
- select dropdown 에서 button only 스타일 수정
> fix: remove isBeta from tab

- src/inputs/buttons/icon-button/PIconButton.stories.mdx
- src/inputs/buttons/icon-button/PIconButton.vue
- src/inputs/buttons/icon-button/story-helper.ts
- src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- Icon Button 에 변경된 스타일 적용
- Select Dropdown 컴포넌트가 button only 인 경우에 disabled, active(visible menu) 스타일이 적용되지 않는 버그 수정
> feat: apply updated icon button style and apply disabled and active style to select dropdown button only case

- src/inputs/buttons/icon-button/PIconButton.vue
- src/inputs/dropdown/select-dropdown/PSelectDropdown.stories.mdx
- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
- src/inputs/dropdown/select-dropdown/story-helper.ts
- select dropdown 에 without outline 케이스 추가 
- icon button 에 focus, active 상태의 스타일 추가
> feat: add without outline case to select dropdown and add focus, active style to icon button

- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
fix: remove min-width from select dropdown button only case
> feat: add icons and lotties

- src/inputs/dropdown/select-dropdown/PSelectDropdown.vue
fix: update props from outline to without-outline  in select dropdown
> fix: update props from outline to without-outline  in select dropdown

- src/data-display/badges/PBadge.stories.mdx
- src/inputs/buttons/copy-button/PCopyButton.vue
- src/navigation/toolbox/PToolbox.vue
- copy button 호버 스펙 변경사항 적용하였습니다.
- toolbox 마이너한 스타일, placeholder 버그 수정하였습니다.
> feat: update copy button hover styling and fix toolbox minor bugs

- src/inputs/buttons/button/PButton.stories.mdx
로딩 케이스에 lottie 가 두 개 생기는 버그를 수정하였습니다.
> docs: fix button story loading case bug

- src/inputs/datetime-picker/PDatetimePicker.vue
* datepicker styling
* @yuda110 님, date/time 선택할때, input resize 스크립트 실행되도록 분리 부탁드립니다.
> style: datepicker style

- .storybook/preview.js
- src/inputs/context-menu/PContextMenu.stories.mdx
- src/inputs/search/search-dropdown/PSearchDropdown.stories.mdx
- src/inputs/search/search-dropdown/PSearchDropdown.vue
- src/inputs/search/search-dropdown/story-helper.ts
- src/inputs/search/search-dropdown/type.ts
- src/inputs/search/search/PSearch.stories.mdx
- src/inputs/search/search/PSearch.vue
- src/inputs/search/search/story-helper.ts
- src/inputs/search/search/type.ts
> fix: add invalid style to search, search dropdown

- src/inputs/buttons/toggle-button/PToggleButton.vue
> fix: change unchecked color of ToggleButton

- src/navigation/toolbox/PToolbox.vue
> fix: remove simple style layout of toolbox

- src/styles/colors.js
콘솔에서 확인하다보니 너무 찐해 문제가 되는 컬러들이 있어 조금 더 밝게 수정했습니다 😂
> feat: change some color more lighter

- src/data-display/dynamic/dynamic-field/PDynamicField.stories.mdx
- src/data-display/dynamic/dynamic-field/PDynamicField.vue
- src/data-display/dynamic/dynamic-field/templates/list/index.vue
- src/data-display/dynamic/dynamic-layout/templates/item/index.vue
- src/data-display/titles/page-title/PPageTitle.stories.mdx
- src/data-display/titles/page-title/PPageTitle.vue
- src/inputs/anchors/PAnchor.vue
- src/inputs/buttons/copy-button/PCopyButton.vue
- src/others/console/text-list/PTextList.vue
> fix: fix css issues in Anchor, CopyButton, DynamicField, PageTitle components

- src/feedbacks/loading/data-loader/PDataLoader.vue
> fix: restructure hierarchy of html and css in DataLoader for loader min height bug fix

- src/feedbacks/loading/data-loader/PDataLoader.vue
> fix: make skeleton loader height full in DataLoader

- src/data-display/tree/PTree.vue
> fix: catch error when getting parent node in Tree

- src/data-display/dynamic/dynamic-layout/PDynamicLayout.stories.mdx
- src/data-display/dynamic/dynamic-layout/PDynamicLayoutPlayground.stories.mdx
- src/data-display/dynamic/dynamic-layout/story-helper.ts
- src/data-display/dynamic/dynamic-layout/templates/html/html.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/item/item.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/list/list.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/markdown/markdown.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/query-search-table/index.vue
- src/data-display/dynamic/dynamic-layout/templates/query-search-table/query-search-table.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/query-search-table/story-helper.ts
- src/data-display/dynamic/dynamic-layout/templates/raw-table/index.vue
- src/data-display/dynamic/dynamic-layout/templates/raw-table/raw-table.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/raw-table/story-helper.ts
- src/data-display/dynamic/dynamic-layout/templates/raw/raw.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/simple-table/simple-table.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/table/index.vue
- src/data-display/dynamic/dynamic-layout/templates/table/story-helper.ts
- src/data-display/dynamic/dynamic-layout/templates/table/table.stories.mdx
- src/data-display/dynamic/dynamic-layout/type/index.ts
- src/data-display/dynamic/dynamic-layout/type/layout-schema.ts
> feat: remove searchable from typeOptions & add disable_search to schema options in DynamicLayout

- src/data-display/badges/PBadge.vue
Change green200 badge's text color for readability
> fix: change green200 badge's text color

- src/data-display/dynamic/dynamic-field/templates/more/index.vue
- src/data-display/dynamic/dynamic-layout/mock.ts
- src/data-display/dynamic/dynamic-layout/templates/item/index.vue
- src/data-display/dynamic/dynamic-layout/templates/item/item.stories.mdx
- src/data-display/dynamic/dynamic-layout/templates/popup/index.vue
- src/data-display/dynamic/dynamic-layout/templates/query-search-table/index.vue
- src/data-display/dynamic/dynamic-layout/templates/simple-table/index.vue
- src/data-display/dynamic/dynamic-layout/templates/table/index.vue
- src/feedbacks/modals/button-modal/PButtonModal.vue
- src/inputs/buttons/copy-button/PCopyButton.vue
> feat: make more type field work in dynamic layout table types

- src/foundation/icons/p-icons/ic_code-collapse.js
> fix(icon): wrong icon name

- .github/PULL_REQUEST_TEMPLATE.md
- From now on, `Skip` is available on ```style / chore``` only
- Added "Not that difficult" => The reviews which is used to skip,
- Added checklist  ```Error / Warning / Lint / Type```. Please fix these before merge
> chore(pr-template): update `skip` / `checklist`

- src/inputs/dropdown/search-dropdown/PSearchDropdown.vue
SSIA
Resolves https://github.com/spaceone-dev/console/pull/3183
> feat(search-dropdown): hide menu by force when disabled

- AUTHORS
> docs(AUTHORS): add new developers

- src/feedbacks/modals/button-modal/PButtonModal.vue
- src/feedbacks/modals/modal.pcss
- make box-shadow for `absolute` modal
- set max height for `absolute` modal
> fix(button-modal): styles

- src/feedbacks/modals/button-modal/PButtonModal.vue
> fix(button-modal): set `max-height` at `absolute` modal
